version: 1
snapshot:
  widths: [1600]
  percy-css: |
    iframe {
      display: none;
    }
agent:
  asset-discovery:
    allowed-hostnames:
      - cdn.ui.porsche.com
      - js-agent.newrelic.com
      - my-static02.porsche.com
