# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


parameters:
- name: build_id
  displayName: Build Id
  type: string
  default: N/A

- name: username
  displayName: BrowserStack User Name
  type: string
  default: N/A

- name: access_key
  displayName: BrowserStack Access Key
  type: string
  default: N/A

trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    echo "Hello World"
    echo "AGENT_WORKFOLDER is $AGENT_WORKFOLDER"
    echo "AGENT_WORKFOLDER contents:"
    ls -1 $AGENT_WORKFOLDER
    echo "AGENT_BUILDDIRECTORY is $AGENT_BUILDDIRECTORY"
    echo "AGENT_BUILDDIRECTORY contents:"
    ls -1 $AGENT_BUILDDIRECTORY
    echo "SYSTEM_HOSTTYPE is $SYSTEM_HOSTTYPE"
    echo "Over and out."
  displayName: 'Run a multi-line script'



- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: output.txt
